### ISSUE TITLE
Suggestion: allow for exact matching of names

### ISSUE THREAD

**Issue by TheEpicBlock** [linkie/linkie-core#1]
Example usage is when looking up obfuscated names. When searching `!ym ddn/d`. It will list all methods that contain a 'd', instead of just the method named 'd'. This results in getting all of the methods in `ddn`. Whilst the behaviour can be useful in some cases, being able to disable it would be nice.

**Comment by shedaniel** [comment]
The actual suggestion will not be considered at the moment, but I have pushed an update to match `ddn/d` properly, which will put the methods named `d` on the first page.
